### ISSUE TITLE
Metric：SAAS service operation observation data indicators（SAAS 服务观测数据指标）

### ISSUE THREAD

**Issue by normal-coder** [oss-compass/compass-web-service#18]
为保证服务运行情况可感知，需要提供对 SAAS 服务的数据指标观测能力，包含如下：

- 采集端
  - 当前平台持有的 Token 数量
  - 当前 Token 池负载（单位周期已消耗、单位周期总次数、整体负载率）
  - 单个 Token 的负载（单位周期已消耗、单位周期总次数、当前 Token 负载率）

- 队列侧
    - 队列中的 Gitee、GitHub 项目数
    - 当前队列中不同更新类型的项目数（数据更新、数据抓取、报告生成）

- 报告数据
    - 当前系统收录的 Gitee、GitHub 的项目数 *（单仓/Community/总数）
    - 当前系统现在存在报告的 Gitee、GitHub 项目数 *（单仓/Community/总数）
    - 当前系统数据已采集完成的 Gitee、GitHub 项目数 *（单仓/Community/总数）
    - 当前系统数据待采集完成的 Gitee、GitHub 项目数 *（单仓/Community/总数）

- 服务侧
    - 服务运作的机器负载/IO 情况
    - 带宽

**Comment by EdmondFrank** [comment]
![image](https://user-images.githubusercontent.com/13914416/232943302-0d8d0228-3cc2-4f7b-9a3d-ab2ec07bb9b6.png)

**Comment by eyehwan** [comment]
Looks great!
