### ISSUE TITLE
Back End: Pipeline time cost evaluation and tuning（pipeline流程各步耗时及优化）

### ISSUE THREAD

**Issue by eyehwan** [oss-compass/compass-web-service#5]
对现有服务数据、运行情况进行统计，分析评估服务的负载能力。

```[tasklist]
### 待确认数据
- [ ] 平均一周可更新的项目数量（冷启动） 
- [ ] 平均一周可更新的项目数量（增量数据） 
- [ ] 单周 Token 平均消耗情况
- [ ] 现有平台
    - [ ] 项目总量（GitHub、Gitee 两个数）
    - [ ] 已完成报告分析的项目数量（GitHub、Gitee两个数）
    - [ ] 待冷启动数量（GitHub、Gitee 两个数）
```

**Comment by EdmondFrank** [comment]
1. 上周更新报告的项目数： 7436 (冷启+增量)
2. 单周Token平均消耗情况无法统计
3. 现在存在报告的Gitee项目数：10965, 采集完数据的总共(11357)
4. 现在存在报告的Github项目数：1845，采集完数据的总共 (3497)
5. 队列中存在任务数：15328 (Gitee + Github)
6. 待冷启动的数量 < 15328

**Comment by lishengbao** [comment]
看看耗时的点主要在哪里？
1. 冷起耗时：
    1.1  总体时间分布；
    1.2 不同阶段时间分布；组建耗时分布；
2. 增量耗时：
    2.1 总体时间分布；
    2.2 不同阶段时间分布；
    2.3 组建耗时分布。

**Comment by lishengbao** [comment]
后端数据issue2，pr2 冗余raw index将会去掉

**Comment by EdmondFrank** [comment]
现在存在报告的Gitee项目数：11363, 采集完数据的总共(11363)
现在存在报告的Github项目数：4014，采集完数据的总共 (4214)
队列中存在任务数：14868 (历史) + 3108 （分类+PR新增+定时刷新）

**Comment by EdmondFrank** [comment]
![Image](https://user-images.githubusercontent.com/13914416/231671638-f2e485ed-ed86-4321-9ee4-9e5b5af06446.png)
