### ISSUE TITLE
Case sensitivity of project names（项目名称大小写敏感问题）

### ISSUE THREAD

**Issue by lishengbao** [oss-compass/compass-web-service#69]
1：在Compass中已存在 https://github.com/Tencent/ncnn 项目，但是用户还可以提交 https://github.com/tencent/ncnn ， 导致原因是Compass项目名是大小写敏感
2：github api项目名大小写不敏感，gitee api项目名大小写敏感，Compass能否兼容这两种情况

**Comment by EdmondFrank** [comment]
Compass 就是要大小写敏感才能兼容这两种情况
